version: '3.8'

services:

  nginx:
    ports:
      - 3000:80

  api:
    build:
      args:
        - NODE_ENV=development
    command: npm run dev

  client:
    build:
      args:
        - NODE_ENV=development
    command: npm start
