version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yash
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    image: api:1.0.0
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    depends_on:
      - mongo

  client:
    image: client:1.0.0
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - api

volumes:
  mongo-db:
